name: recipe_app
description: "A new Flutter project."

# Versi aplikasi
version: 1.0.0+1

# Batasan versi SDK Dart
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.3.0 # Versi terbaru dari package http
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Tambahkan aset jika ada
  assets:
    - assets/


